# Generated by Django 4.0.3 on 2022-06-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
