# Generated by Django 3.2.9 on 2021-11-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_comment_commentdislike_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='name',
        ),
    ]
