# Generated by Django 3.2.9 on 2021-11-24 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_auto_20211124_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='video.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='commentdislike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('user', 'video')},
        ),
    ]
