# Generated by Django 4.0.3 on 2022-04-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20211124_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='banner',
            field=models.FileField(null=True, upload_to='storage/image/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='storage/video/'),
        ),
    ]
