# Generated by Django 3.2.9 on 2022-04-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_remove_video_tags_tag_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='video.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
