# Generated by Django 3.2.9 on 2022-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20220421_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dtype',
            field=models.CharField(choices=[('video', 'Default'), ('short', 'Back'), ('stream', 'Front')], default='video', max_length=64),
            preserve_default=False,
        ),
    ]
