# Generated by Django 3.2.9 on 2022-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20220421_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='video_type',
            field=models.CharField(choices=[('video', 'Video'), ('short', 'Short'), ('stream', 'Stream')], default='video', max_length=64),
            preserve_default=False,
        ),
    ]
